### ISSUE TITLE
Obsolete elements

### ISSUE THREAD

**Issue by tobolar** [dzimmer/PlanarMechanics#189]
## Delete obsolete parameters
(see [ConvertFromPlanarMechanics_2_0_0.mos](https://github.com/dzimmer/PlanarMechanics/blob/master/PlanarMechanics/Resources/Scripts/Conversion/ConvertFromPlanarMechanics_2_0_0.mos))
- [x] `PlanarMechanics.Sources.RelativeForce`:
    - `diameter`
- [x] `PlanarMechanics.Sources.WorldForce`:
    - `diameter`
- [x] `PlanarMechanics.Sources.QuadraticSpeedDependentForce`:
    - `diameter`
- [x] `PlanarMechanics.Sensors.CutForce`:
    - `forceDiameter`
- [x] `PlanarMechanics.Sensors.CutForceAndTorque`:
    - `forceDiameter`
    - `torqueDiameter`
- [x] `PlanarMechanics.Sensors.CutTorque`:
    - `torqueDiameter`

## Delete obsolete types without replacement
- [x] `PlanarMechanics.Types.SpecularCoefficient` - see also #187 
- [x] `PlanarMechanics.Types.Color` - see also #187 
- [x] Move `Visualizers.Advanced.DoubleArrow` into obsolete, use Arrow or Vector(torque) instead (depending on the resolution of https://github.com/modelica/ModelicaStandardLibrary/issues/3931).
Resolved - see #219 
---
- [x] Mark all changes in Release Notes
